# Generated by Django 3.2.9 on 2021-11-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
